apiVersion: v1
kind: Service
metadata:
  name: java-springboot-api-service
spec:
  selector:
    app: java-springboot-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
