apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-springboot-api
  labels:
    app: java-springboot-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-springboot-api
  template:
    metadata:
      labels:
        app: java-springboot-api
    spec:
      containers:
        - name: java-springboot-api
          image: fredwinrosales/java-springboot-api:latest
          ports:
            - containerPort: 8080
